### ISSUE TITLE
exit vs. sys.exit

### ISSUE THREAD

**Issue by tomschr** [Syntaf/travis-sphinx#13]
Not sure if this is worth an issue, but I saw there is `exit()` and `sys.exit()`. Not sure why you use sometimes the first and sometime the last function. Both seem to do mostly the same.

Could it be use consistently?

**Comment by Syntaf** [comment]
Removed use of exit. [ref](http://stackoverflow.com/questions/6501121/the-difference-between-exit-and-sys-exit-in-python)
