### ISSUE TITLE
Require ghp_import in setup.py?

### ISSUE THREAD

**Issue by tomschr** [Syntaf/travis-sphinx#14]
I observed you use the `ghp_import.py` script from the [`ghp_import`](https://github.com/davisp/ghp-import) repository.

The interesting part is line 49 where you clone the repository with git and execute it (function `deploy_docs`). I'm not sure what the story behind this design decision is, but this is a bit, well... unusual. ;-)

The problem with this approach is:
- It's not pythonic. ;-)
- When you install it, it doesn't retrieve all requirements. Pip doesn't install `ghp_import` automatically.
- Other programs which read `setup.py` and check for requirements cannot get the "full" list of requirements (because `ghp_import` is "hidden" inside your script).

Is there a reason why you don't require this in the project? I would propose the following changes:
- State clearly in `setup.py` that this project requires `ghp_import`:
  
  ``` python
  install_requires=[
      'sphinx', 'ghp_import',
  ],
  ```
- If possible, don't clone the repo and run the script. Instead import it and use it as follows:
  
  ``` python
  import ghp_import
  
  # This is unfortunately needed by ghp_import
  import optparse as op
  
  def deploy_docs(target_dir, branches, pr_flag):
    #...
    # Not sure about this; I consider it a hack to use `check_repo()`.
    # Maybe send a pull request to improve it?
    parser = op.OptionParser(usage=ghp_import.__usage__, option_list=ghp_import.options())
    # Only needed when you want to check the repo:
    ghp_import.check_repo(parser)
  
    # Replace the following line with the 
    #   run('./ghp-import/ghp_import.py', '-n', 'target/doc/build')
    gh_import.run_import('target/doc/build', # source directory
             'gh-pages', # branch
             'Updated documentation with travis-sphinx', # commit message
             nojekyll=True):
  ```

Probably the `ghp_import.py` wasn't meant to be a library but a script. Maybe the upstream project should split the script into a library part and a script part. That would make things easier for you.

If the last entry from the above list doesn't work, you could just run the `ghp_import.py` script.

How does it sound? :-)

**Comment by Syntaf** [comment]
I'm remembering now why I implemented `deploy_docs` that way. The issue is that `ghp_import` is not designed to be use as a calling interface, it's a console script. Installing ghp_import doesn't actually let you import the module, the only file available from the install is `ghp-import` , no file extension. 

I used run simple because it used `ghp_import` as it was designed to be used.

**Comment by tomschr** [comment]
Yes, maybe it was a bad idea. ;-)

However, maybe you should add this line to your `setup.py` to state a dependency to `ghp_import`:

```
install_requires=[
    'sphinx', 'ghp_import',
],
```

**Comment by Syntaf** [comment]
With the 2.0.0 changes, this issue is no longer applicable. Thanks for the issue none the less!
