### ISSUE TITLE
Allow non-force push

### ISSUE THREAD

**Issue by tomschr** [Syntaf/travis-sphinx#15]
Currently, travis-sphinx [force push to the gh-pages branch](https://github.com/Syntaf/travis-sphinx/blob/master/travis_sphinx.py#L51). Some use cases consider this force push as unfortunate.

For example, sometimes it would be helpful to go back to previous releases to see what is there. Although this can be done with your other branches too, but the gh-pages branch contains only the result, not the sources.

I would propose to add an option (for example, `--no-force-push` or the like) which does just a normal push to the gh-pages branch instead of a force push.

**Comment by Syntaf** [comment]
The only issue with no force pushes is you will bloat your repository significantly with each commit. Sphinx generates a lot of intermediate files, making small changes is going to add lots of changes to each commit. 

I would argue that if a user wanted to revert their auto generated docs, they should revert their repository to do so. It doesn't make too much sense reverting to an earlier version of the website yet keeping the repository current.

**Comment by tomschr** [comment]
> The only issue with no force pushes is you will bloat your repository significantly with each commit. Sphinx generates a lot of intermediate files, making small changes is going to add lots of changes to each commit.

Ok, that's true. So let's close it for the time being. :-) Thanks for reading.
