### ISSUE TITLE
Specify output directory

### ISSUE THREAD

**Issue by pancetta** [Syntaf/travis-sphinx#19]
By default `travis-sphinx build` generates the html files under `target/doc/build`. Yet, there seems to be an undocumented flag called `--outdir` which can change this behavior. Are there any side effects when using this (e.g. during deploy)? Could you document this in the README.md?

**Comment by Syntaf** [comment]
This was added at https://github.com/Syntaf/travis-sphinx/pull/7

I'll add the docs for it when I get the chance (currently out of town). Thanks!
