### ISSUE TITLE
Pypi version is not compatible with python3

### ISSUE THREAD

**Issue by reno-** [Syntaf/travis-sphinx#2]
I just tried your module and it's a nice tool !! 
But the pypi version seems outdated. Could you please update your module on pypi?
cheers,
reno-

**Comment by Syntaf** [comment]
Hey reno, thanks! I believe you're right in that it is missing https://github.com/Syntaf/travis-sphinx/pull/1. I'll update the pypi module

**Comment by Syntaf** [comment]
Should be uploaded now, can you confirm it works?

**Comment by reno-** [comment]
Thank you, now it works smoothly !!
