### ISSUE TITLE
`-b` and `-p` not properly handled

### ISSUE THREAD

**Issue by b52** [Syntaf/travis-sphinx#20]
[Both options (`branches` and `pullrequests`)](https://github.com/Syntaf/travis-sphinx/blob/master/travis_sphinx.py#L107-L109) are parsed against an incorrect option tag, thus only the long text versions for both properties work correctly.

**Comment by Syntaf** [comment]
whoops, you're right. I'll fix this asap

**Comment by Syntaf** [comment]
https://github.com/Syntaf/travis-sphinx/commit/5323c60155585f53681e6cd2e324c98ea60a580e

**Comment by Syntaf** [comment]
Currently out of town, so i'll update the pypi repo once i'm back at my house.

**Comment by b52** [comment]
Thanks!
