### ISSUE TITLE
GitHub access token revealed in travis-ci log on failed deploy

### ISSUE THREAD

**Issue by phantomas1234** [Syntaf/travis-sphinx#21]
This line https://github.com/Syntaf/travis-sphinx/blob/master/travis_sphinx.py#L51 will dump the personal access token right into the travis-ci log if the push to github fails.

```
3.52s$ if [[ $TRAVIS_PYTHON_VERSION == "3.6" ]]; then travis-sphinx --branches=feat-publish-docs-through-travis-ci,devel --pullrequests deploy; fi
uploading docs...
Cloning into 'ghp-import'...
remote: Counting objects: 305, done.
remote: Total 305 (delta 0), reused 0 (delta 0), pack-reused 305
Receiving objects: 100% (305/305), 75.33 KiB | 0 bytes/s, done.
Resolving deltas: 100% (164/164), done.
remote: Permission to biosustain/cameo.git denied to phantomas1234.
fatal: unable to access 'https://a19ddaff2be5282e36a77512f28ebadde9b3a86c@github.com/biosustain/cameo.git/': The requested URL returned error: 403```

**Comment by Syntaf** [comment]
wuh oh, that's not very good. Looks like travis-sphinx should probably turn off output during that phase instead of piping the direct output. Let me label this as a bug and maybe i'll get to it this weekend unless you'd want to make a PR on this

**Comment by jakirkham** [comment]
As a workaround, you could redirect everything to `/dev/null`. Not ideal, but it would hide the token on failure.

**Comment by Syntaf** [comment]
should successfully hide token on error now
