### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jakirkham** [Syntaf/travis-sphinx#22]
What is the license of this code?

Edit: Also would be nice to have this metadata in `setup.py`, a license file, and inclusion of the license file in the `MANIFEST.in`.

**Comment by Syntaf** [comment]
Feel free to use the code for whatever means you wish, whether it be commercial use or personal use.

A mention would be nice, but Is not required in any way.

**Comment by jakirkham** [comment]
So like MIT? Or like CC0?

**Comment by hoijui** [comment]
legally, as long as you apply no license, it means "All rights reserved". this means that if we just use your project, you could potentially sue us, or ask us to not use it anymore (which might cause lots of work for us), or you could sell the project to someone who will then sue us, ... simply put, it leaves users of the project vulnerable.
So it owuld be nice if you coudl actually put it under a license, as sometimes this is even a hard requirement for using it (in my case for example, we are an open hardware NPO).
.. pleaaaase! :D ;-)

**Comment by Syntaf** [comment]
@hoijui I went ahead and added a license, hopefully you'll be able to use this tool now!

**Comment by hoijui** [comment]
perfect, thank you! :-)
