### ISSUE TITLE
Default source changed

### ISSUE THREAD

**Issue by mrichar1** [Syntaf/travis-sphinx#28]
Docs say `source` will be `docs/source` but https://github.com/Syntaf/travis-sphinx/commit/143798b1252076aedb7d46be14960843ee5cb49f sets this to now be `doc/source`

**Comment by Syntaf** [comment]
Whoops, this change was not intended. When I'm back home today i will fix this and update the pypi repo ASAP

Thanks for the bug report!

**Comment by mrichar1** [comment]
Having now run it a few times it actually seems to make 2 changes: source: docs/source -> doc/source and output: target/docs/build -> doc/build (though the latter is less critical). Thanks for having a look at this!

**Comment by Syntaf** [comment]
Should be fixed in https://pypi.python.org/pypi/travis-sphinx/2.0.1 , let me know if I broke more stuff :)
