### ISSUE TITLE
Deploy triggered for non-master branch '': skipping deploy

### ISSUE THREAD

**Issue by pazz** [Syntaf/travis-sphinx#45]
I have followed the instructions in the README but still cannot deploy to github.
Below is a local log, which I did in the `master` branch of my project. Notice that `GH_TOKEN` is explicitly set before the call to deploy (on travis, I set it via settings as outlined in the README).

`travis-sphinx`: installed using `pip3` on a debian testing machine.
Python: 3.6.7

```
travis-sphinx build 
Running Sphinx v1.8.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: [] 0 added, 2 changed, 0 removed
reading sources... [100%] api/utils                                                                                      
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                           
generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

The HTML pages are in doc/build.


export GH_TOKEN=b044f3dc1...rest..of..token
travis-sphinx -v deploy
Deploy triggered for non-master branch '': skipping deploy
```

**Comment by pazz** [comment]
[here](https://gist.github.com/pazz/efa3ef4e139755812b5fd0934a993f1a) is a full log from travis.

**Comment by pazz** [comment]
It seems that I misconfigured my travis config. I can now upload docs as expected.
Further, for the local behaviour, I seem to have overlooked that it is necessary to set several environment variables, which are read by travis-sphinx.

**Comment by Syntaf** [comment]
Hey sorry for the late response, been a bit busy over here. Thanks for the issue none the less and glad you figured it out @pazz !
